### ISSUE TITLE
undefined sympol

### ISSUE THREAD

**Issue by cyk2018** [pytorch/extension-cpp#103]
When I follow the tutorial and try "python test/test_extension.py", I found this error below:
```
Traceback (most recent call last):
  File "/gemini/code/extension-cpp-master/test/test_extension.py", line 5, in <module>
    import extension_cpp
  File "/root/miniconda3/lib/python3.11/site-packages/extension_cpp/__init__.py", line 2, in <module>
    from . import _C, ops
ImportError: /root/miniconda3/lib/python3.11/site-packages/extension_cpp/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit11parseSchemaERKSsb
```
Does anyone know how to fix this?

**Comment by cyk2018** [comment]
I find this [comment](https://github.com/pyg-team/pytorch_geometric/issues/999#issuecomment-593511800) that can solve my problem.
