### ISSUE TITLE
ImportError: No module named 'lltm_cuda'

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/extension-cpp#34]
Hi,Peter
CMD: python3 jit2.py
no result,help, pls ...
Loading extension module lltm_cuda...
Traceback (most recent call last):
  File "jit2.py", line 24, in <module>
    verbose=True
  File "E:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 645, i
n load
    is_python_module)
  File "E:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 825, i
n _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "E:\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 965, i
n _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "E:\Python36\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'lltm_cuda'

**Comment by chouchouxia** [comment]
Me too. Someone help me....
